### ISSUE TITLE
Not finding the Model - GLM3

### ISSUE THREAD

**Issue by Piscabo** [BetaDoggo/ComfyUI-Kolors-Translator#2]
![image](https://github.com/BetaDoggo/ComfyUI-Kolors-Translator/assets/123719842/c16f0a30-873c-4b13-afab-42db00f9c29f)
Models are present, but the node is not finding it.
![image](https://github.com/BetaDoggo/ComfyUI-Kolors-Translator/assets/123719842/73166120-8d50-4b89-bd47-b60a9d7ae911)

**Comment by BetaDoggo** [comment]
This is related to the main extension [KwaiKolorsWrapper](https://github.com/kijai/ComfyUI-KwaiKolorsWrapper), you need to put one of [these models](https://huggingface.co/Kijai/ChatGLM3-safetensors/tree/main) into `\models\LLM\checkpoints`
