### ISSUE TITLE
Promt

### ISSUE THREAD

**Issue by iovart** [BetaDoggo/ComfyUI-Kolors-Translator#3]
I don't have a promt node. Help me

![promt](https://github.com/user-attachments/assets/e5d705ad-910d-40f3-b108-a66f9533852c)

**Comment by BetaDoggo** [comment]
You need to convert the prompt from a widget to an input. 
right-click node->"Convert Widget to Input"->"Convert prompt to input":
![image](https://github.com/user-attachments/assets/eb4a9240-19eb-4d53-8ef2-b39ddbb1a54f)

**Comment by iovart** [comment]
Thanks!
